### ISSUE TITLE
ReferenceError: gameanalytics is not defined | on HTML5

### ISSUE THREAD

**Issue by Jerakin** [GameAnalytics/GA-SDK-DEFOLD#12]
If HMTML 5 isn't supported it would still be awesome if there was a mock implementation that threw the calls away, right now the game crashes.

**Comment by the1schwartz** [comment]
It looks like you might need to add this line to your html5 template file:
`<script type='text/javascript' src="GameAnalytics.js"></script>`

After you have done that it should fix the error you are getting, or else let me know if you are still getting the error.

**Comment by subsoap** [comment]
@Jerakin Make sure you wrap your native extension calls in code such as

```
if gameanalytics then
  ...
end
```

**Comment by Jerakin** [comment]
@subsoap That's a good point, unfortunately I haven't separated the gameanalytics call to a different module so now they are kinda all over my code. 

I ended up doing
```
local system = sys.get_sys_info().system_name
if system == "HTML5" then
	gameanalytics = require "utils.mock_gameanalytics"
end
```
The module only have empty functions. Is this solution fine you think?

**Comment by subsoap** [comment]
@Jerakin If it doesn't break then that is good at least, but you should probably refactor eventually too.

**Comment by Jerakin** [comment]
@the1schwartz After adding it I get this in the console. It doesn't send the tracking.
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.gameanalytics.com/v2/dba33986f167a0297a66e16ffa86787d/events. (Reason: CORS request did not succeed).[Learn More]
Warning/GameAnalytics: Event queue: Failed to send events to collector - Retrying next time GameAnalytics.js:2:8218
```

**Comment by subsoap** [comment]
Try testing on an actual server and not localhost?

**Comment by Jerakin** [comment]
I am not sure what you mean. The app is running from itch.io
I see that I have gotten some data sent. 5 users while the itch analytics shows maybe ~15

**Comment by subsoap** [comment]
Maybe a CORS header is missing on the page and your browser is strict about it while other browsers are not?

**Comment by Jerakin** [comment]
Yeah maybe. I have tried setting it but with no luck (granted my knowledge of html is limited). I read that somewhere that this should be set on the server however. GameAnalytics is calling `https://rubick.gameanalytics.com/v2` and `https://api.gameanalytics.com/v2/` so maybe it is something on their end? Will create a new ticket for it as it isn't related to this (to increase visibility if nothing else)

**Comment by subsoap** [comment]
@the1schwartz what do you think?

**Comment by the1schwartz** [comment]
Our backend team has recently made some changes that potentially could give some problems but we didn't experience them ourselves during our testing but I have asked them now if they think the changes could cause this.
