### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by Jerakin** [GameAnalytics/GA-SDK-DEFOLD#13]
I get CORS errors in my HTML build, and it looks like the data isn't sent on firefox. But I can still see some tracking so I assume/think that some browsers might still work.

The error is from Firefox. Tested on macOS and Windows
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://rubick.gameanalytics.com/v2/command_center?game_key=dba33986f167a0297a66e16ffa86787d&interval_seconds=1000000. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.gameanalytics.com/v2/dba33986f167a0297a66e16ffa86787d/events. (Reason: CORS request did not succeed).[Learn More]
```

This error is from Crome.  Tested on Windows
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
api.gameanalytics.com/v2/dba33986f167a0297a66e16ffa86787d/events:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

VM20:1 OPTIONS https://api.gameanalytics.com/v2/dba33986f167a0297a66e16ffa86787d/events net::ERR_BLOCKED_BY_CLIENT
GameAnalytics.js:2 Warning/GameAnalytics: Event queue: Failed to send events to collector - Retrying next time
```

**Comment by the1schwartz** [comment]
Ok do you by any chance have a link to the game you are talking about so I can test it on my end?

**Comment by Jerakin** [comment]
Yeah sorry, should of course have added that: https://jerakin.itch.io/pokedex5e

**Comment by the1schwartz** [comment]
Ok thanks I will try to test it out myself in different browsers to see what i get

**Comment by the1schwartz** [comment]
I don't see any logs in the console for the GA SDK, has it been disabled or what do I need to do to see events in the logs?

**Comment by Jerakin** [comment]
Odd - I still get the same errors.
![Screen Shot 2019-04-29 at 13 34 23](https://user-images.githubusercontent.com/5273682/56893638-a4397600-6a83-11e9-9e49-ea19772f0c22.png)

Maybe if you click and add random stuff in the app so it got something to send?

**Comment by the1schwartz** [comment]
Ok. When I look in the Network tab I can see events are being sent. I have tested for both Chrome, Firefox and Safari.

**Comment by Jerakin** [comment]
Oh, alright. The data have gotten a few more days and it seems to be about right (with a reasonable error margin of what itch and dashboard.defold.com reports). Sorry for the false flag :)
