### ISSUE TITLE
version 2.2.1 breaks HTML5 builds

### ISSUE THREAD

**Issue by MaratGilyazov** [GameAnalytics/GA-SDK-DEFOLD#14]
On try to run web-build made with 2.2.1 GA plugin I see errors inside ProjectName_asm.js and _wasm.js in browser’s console, somewhere on initialisation/loading. And the issue disappears after reverting to 2.2.0.

I was using only Design events.

Build om MacBook Pro 13'' 2018, OSX 10.14.1, Defold 1.2.152

![image](https://user-images.githubusercontent.com/15916299/57287459-d700f100-70b7-11e9-85fc-4df45bab9d65.png)

**Comment by the1schwartz** [comment]
Thanks for reporting this and sorry for inconvenience. This should be fixed now in the latest version (v2.2.2). Let me know if you still experience any other problems.
