### ISSUE TITLE
Fail to install on Android Phone when the build include 64-bit

### ISSUE THREAD

**Issue by kibot914** [GameAnalytics/GA-SDK-DEFOLD#16]
Thanks for fixing the bugs on issue #15 

However, it still has another issue even it can successfully generate the apk file.
It fails to install on Android Phone when the 64-bit option is checked.

<img width="635" alt="Screenshot 2019-05-23 at 9 59 33 AM" src="https://user-images.githubusercontent.com/13725006/58220657-54786280-7d42-11e9-8781-864d74029f1f.png">

**Comment by the1schwartz** [comment]
I can install a arm-64 android app with the GA SDK with no problems. I don't think the error is specifically related to the above error code. This is what the documentation says about the error:

> Installation return code: this is passed in the {@link PackageInstaller#EXTRA_LEGACY_STATUS} if the new package failed while optimizing and validating its dex files, either because there was not enough storage or the validation failed.

**Comment by kibot914** [comment]
> I can install a arm-64 android app with the GA SDK with no problems. I don't think the error is specifically related to the above error code. This is what the documentation says about the error:
> 
> > Installation return code: this is passed in the {@link PackageInstaller#EXTRA_LEGACY_STATUS} if the new package failed while optimizing and validating its dex files, either because there was not enough storage or the validation failed.

Alright thanks for the prompt reply, let me double check everything
