### ISSUE TITLE
"Fail" progression events sent as "Complete"

### ISSUE THREAD

**Issue by selimanac** [GameAnalytics/GA-SDK-DEFOLD#17]
Simple "Fail" progression event like this:

```lua
gameanalytics.addProgressionEvent {
        progressionStatus = "Fail",
        progression01 = "UserLevel_",
        progression02 = "GameLevel_" ,
        score = 100
    }
```
Sent as "Complete"

`Info/GameAnalytics: Add PROGRESSION event: {status:Complete, progression01:UserLevel_, progression02:GameLevel_, progression03:, score:100, attempt:0, fields:null}`

And "Fail" progression events doesn't appear on dashboard

Edit: It works on iOS but not on MacOS

**Comment by the1schwartz** [comment]
Thanks for reporting this. The bug should be fixed in the latest version (v2.2.4)
