### ISSUE TITLE
Not reciving events on Android

### ISSUE THREAD

**Issue by Jerakin** [GameAnalytics/GA-SDK-DEFOLD#18]
I have stopped receiving events on Android after (I think) Defold 1.2.153 
iOS still receives all events

**Comment by the1schwartz** [comment]
i have just tested for android using 1.2.156 and it looks to work fine :/

**Comment by Jerakin** [comment]
Thanks for verifying - must be on my end then. I don't get any errors in the console that I can see from adb - any ideas how best to troubleshoot this?

**Comment by the1schwartz** [comment]
Errors as in crash errors or what do you mean?

**Comment by Jerakin** [comment]
Solved it a the secret key was incomplete a number had fallen away at some point. I assume it doesn't check the length or anything of the string so it didn't warn.

**Comment by the1schwartz** [comment]
Ok great you figured what the problem was. The SDK should validate the keys also on length and give a warning if they are not valid it terms of length and only invalid type of characters. Weird you didn't get the warning :/
