### ISSUE TITLE
Warning/GameAnalytics: Event queue: Failed to send events.

### ISSUE THREAD

**Issue by subsoap** [GameAnalytics/GA-SDK-DEFOLD#19]
This happens sometimes, the only solution seems to manually delete 

C:\Users\User\AppData\Local\GameAnalytics

But there should probably be a built in way to deal with this and recover

```
Warning/GameAnalytics: Event queue: Failed to send events.
```

**Comment by the1schwartz** [comment]
Ok does this only happens when trying to send session end event on closing down application, or do you have a way to replicate this?

**Comment by subsoap** [comment]
It happens while running the application I think when the log gets too large, I have not seen it in a while but got report that deleting the log fixed it, I saw that same thing too months ago and also deleted the GA local appdata folder to fix it. Maybe a way to simulate it would be to create too many events.

**Comment by the1schwartz** [comment]
Ok thanks for the feedback. We have updated the C++ library to only log 5000 log lines per file (it will save the last previous 5000 logs in a prev file). Let me know if it is still causing this issue.
