### ISSUE TITLE
Documentation missing HTML5 parts

### ISSUE THREAD

**Issue by subsoap** [GameAnalytics/GA-SDK-DEFOLD#2]
https://forum.defold.com/t/defold-integration-for-gameanalytics-def-3024/10417/27?u=pkeod

**Comment by the1schwartz** [comment]
Should be fixed now

**Comment by Jerakin** [comment]
It isn't there anymore
![Screenshot 2019-10-03 at 10 30 07](https://user-images.githubusercontent.com/5273682/66111272-d28a2700-e5c8-11e9-85cd-4525de9034ce.png)

**Comment by the1schwartz** [comment]
Sorry thanks for reporting this. Fixed again. I guess it missing to proper escape some of the character for html.
