### ISSUE TITLE
win32 builds crash with latest Defold version

### ISSUE THREAD

**Issue by subsoap** [GameAnalytics/GA-SDK-DEFOLD#25]
Make a blank project

Add game key/secret to game.project

Bundle for windows 32 (64 works fine)

Defold writes a crash dump

Might be related to latest clang update

**Comment by mathiaswking** [comment]
What dependencies did you use for this?

**Comment by the1schwartz** [comment]
gdi32.lib
libcurl.lib
libeay32.lib
ole32.lib
ssleay32.lib

**Comment by mathiaswking** [comment]
Oh, I meant, game.project dependencies (i.e. the native extensions)

**Comment by the1schwartz** [comment]
Ah ok not dependent on any other native extensions

**Comment by subsoap** [comment]
@mathiaswking I tested with this extension only. A blank project with this extension on win32 does not crash. You must include game/secret key in the game.project file for it to crash. If you need I can provide _crash and debug symbols.

**Comment by mathiaswking** [comment]
It seems they've found the crash in their lib for Win32, and are making a new release (https://forum.defold.com/t/extender-server-ios-13-osx-10-15-clang-9/63569/35?u=mathias_westerdahl)

**Comment by the1schwartz** [comment]
This should be fixed in the latest version now (v2.3.1). Let me know if it still 
happens for you.

**Comment by the1schwartz** [comment]
Thanks. That should be fixed as well now.
