### ISSUE TITLE
Docs issue

### ISSUE THREAD

**Issue by subsoap** [GameAnalytics/GA-SDK-DEFOLD#26]
https://gameanalytics.com/docs/item/defold-sdk#gameanalytics-addbusinessevent
```
itemType (Number): amount in cents
```
This doesn't seem right based on the examples lower on

Also signature is not listed as an option even though it's listed as an example below

![2019-10-24 03_04_11-Defold SDK - GameAnalytics](https://user-images.githubusercontent.com/409170/67475400-f8747b80-f60a-11e9-8558-de2c513f8cb2.png)

Some of the other text here isn't super clear either, could use a second look/rewrite.

**Comment by subsoap** [comment]
Looking at another SDK it looks like some things got messed up on the Defold one

![2019-10-24 03_06_11-Construct SDK - GameAnalytics](https://user-images.githubusercontent.com/409170/67475545-42f5f800-f60b-11e9-907f-b483941de521.png)

**Comment by the1schwartz** [comment]
Yeah it looks like the description for **itemType** and **amount** got swapped around. It should be fixed now.

**Comment by subsoap** [comment]
@the1schwartz it would be a really sweet feature if GA provided on the fly receipt validation and not just for analytics... I'm looking into integrating playfab now just because they provide that.

**Comment by the1schwartz** [comment]
We could probably support that feature as we do receipt validation (but delayed) in our backend for business event with attached receipts. What is your use case if I may ask. You are welcome to write to sdk@gameanalytics.com if you want to take this discussion elsewhere :)

**Comment by subsoap** [comment]
I want to avoid our full version unlock IAPs being easy to unlock with store emulators and to validate consumable IAPs too before granting them in game. Mostly to annoy pirates since they annoy me. 😇 But I have heard from some devs that $ increased after they began to validate since doing custom hacks is much rarer for games and most pirates don't bother if the all in one store emulator/patchers don't work, if they love a game they can actually be converted to a paying customer if piracy is not so easy.

I would rather use GA if you add the feature! The way PlayFab handles it is more roundabout than I want - they validate receipts but then add an item to a player's inventory.
