### ISSUE TITLE
GAs possibly causing ANRs on Android when closing app via Defold

### ISSUE THREAD

**Issue by subsoap** [GameAnalytics/GA-SDK-DEFOLD#27]
When doing 
```
msg.post("@system:", "exit", {code = 0})
```
sometimes our Android games will freeze up instead of closing properly. The only NE that probably could do this in one of the games is GA so may be worth investigating.
![2020-03-18 18_28_30-ANRs   crashes - Faerie Solitaire Remastered - Google Play Console](https://user-images.githubusercontent.com/409170/77194317-fa007d80-6a9c-11ea-8bf5-156c7aca5519.png)
![2020-03-18 18_28_54-ANRs   crashes - Faerie Solitaire Remastered - Google Play Console](https://user-images.githubusercontent.com/409170/77194319-fa991400-6a9c-11ea-9a8e-56f1fba8f79f.png)
![2020-03-18 18_29_39-ANRs   crashes - Faerie Solitaire Remastered - Google Play Console](https://user-images.githubusercontent.com/409170/77194320-fb31aa80-6a9c-11ea-972f-43993b526da1.png)
![2020-03-18 18_29_50-ANRs   crashes - Faerie Solitaire Remastered - Google Play Console](https://user-images.githubusercontent.com/409170/77194321-fb31aa80-6a9c-11ea-8fc1-4224fe62db8d.png)

**Comment by the1schwartz** [comment]
Ok thanks for reporting this. I will have a look into it.

**Comment by the1schwartz** [comment]
Sorry to ask what does NE stand for?

**Comment by the1schwartz** [comment]
I have make some changes/improvements to the SDK's event processing thread (in the Android library). I am not what else could cause issues when closing the app. I have tested myself with calling "msg.post("@system:", "exit", {code = 0})" but could not reproduce the issue. The fix is in the latest version of the Defold SDK (v3.1.6). Let me know if you are still experiencing the issue.

**Comment by subsoap** [comment]
@the1schwartz NE = Native Extension, GA is the main NE we use, most of the rest is vanilla engine.

It may only show up with enough stuff queued for sending? 

Thank you for the update! I'll make new builds soon and see if we get a reduction in ANRs.

**Comment by subsoap** [comment]
@the1schwartz Whatever you did most likely has reduced ANRs. At least according to our data they are down.

**Comment by the1schwartz** [comment]
Ok great to hear it has helped @subsoap
