### ISSUE TITLE
Custom dimensions do not work properly

### ISSUE THREAD

**Issue by MaratGilyazov** [GameAnalytics/GA-SDK-DEFOLD#28]
I've set two possible values for custom dimensions in game.project as described in [docs](https://gameanalytics.com/docs/item/defold-sdk#configuring-game-project): 
```
[gameanalytics]
custom_dimensions_01 = levels_a,levels_b
```
Then in my code I randomly set one of the values: 
```
if math.random() > 0.5 then
    gameanalytics.setCustomDimension01("levels_a")	
else
    gameanalytics.setCustomDimension01("levels_b")	
end	
```
- **Expected behaviour**: see both "levels_a" and "levels_b" in customDimension01 in the dashboard
- **Actual behaviour**: see only "levels_b" dimension in the dashboard, see the screenshot [https://puu.sh/FuonQ/5bb9d2f9c4.png](https://puu.sh/FuonQ/5bb9d2f9c4.png)

Issue was found in the HTML5 build. sdk_version: defold 3.1.7

Can you check and fix, please?

**Comment by the1schwartz** [comment]
Hi. Have you actually checked the logs in the browser console that customDimension01 is set "levels_a" and that events are being sent with customDimension01 equal to "levels_a". I just did some tests and it seems to work fine. Maybe try to set customDimension01 manually instead of using math.random() so you know exactly when to expect "levels_a" or "levels_b".

**Comment by MaratGilyazov** [comment]
@the1schwartz yes, sorry, my bad - it turned out that my randomseed() function did not worked in HTML5 build so math.random() was always returning the same value here (but it works loacally). Sorry for disturbing. 

Another quick question regarding custom dimensions, it's not clear from docs - does it stay persistent only during current session or it'll be saved for further sessions too? If I want to "mark" my player for his whole lifetime, should I save the mark and apply as customDimension on each session or doing so only once is enough? 

Thanks in advance!

**Comment by the1schwartz** [comment]
Sorry if it is not clear enough in the documentation (will update it) but custom dimensions are persistent between sessions.

**Comment by the1schwartz** [comment]
It should be described here: https://gameanalytics.com/docs/item/defold-sdk#using-custom-dimensions
