### ISSUE TITLE
Q: What functions do you use from OpenSSL?

### ISSUE THREAD

**Issue by JCash** [GameAnalytics/GA-SDK-DEFOLD#31]
I'm asking since we're thinking of exposing certain functions via our own `dmCrypt::` namespace.
We use [mbedTLS](https://github.com/ARMmbed/mbedtls) which is a lot smaller in code side footprint.

Perhaps this won't be of use to you, since your libraries are closed source, but I thought I'd ask anyways, since it will help our decision making, and hopefully others in the longer run.

Regards,
Mathias

**Comment by the1schwartz** [comment]
Hmm I think we just use OpenSSL indirectly HTTPS requests using curl and yes that is all happening in our native C++ library.

**Comment by JCash** [comment]
Ok, good to know.
