### ISSUE TITLE
Make HTML5 target automerge the js include line

### ISSUE THREAD

**Issue by subsoap** [GameAnalytics/GA-SDK-DEFOLD#33]
See https://defold.com/manuals/extensions-manifest-merge-tool/#html5

https://forum.defold.com/t/manifest-merge-tool/52769

Setting this up should make it unnecessary to require this line to be added manually to the template

> <script type='text/javascript' src="GameAnalytics.js"></script>

**Comment by the1schwartz** [comment]
Thanks I will into adding this

**Comment by the1schwartz** [comment]
Ok it should be in the latest version now (v3.3.9)
