### ISSUE TITLE
Failed to run in Editor on macOS

### ISSUE THREAD

**Issue by Lampogolovii** [GameAnalytics/GA-SDK-DEFOLD#35]
1. I've added Game Analytics into my project (I use Defold 1.2.186 release)
2. When I try to run the game in editor - it fails with an error (screenshot)
3. When I build to html5 - everything is OK

<img width="904" alt="Screenshot 2021-08-31 at 18 07 17" src="https://user-images.githubusercontent.com/23137022/131530775-98bf7287-cd26-4c45-902e-dbcfebb2b3a8.png">

**Comment by the1schwartz** [comment]
Hmm, I have tried to run in editor on macOS and I don't have any issues :/

**Comment by Lampogolovii** [comment]
That's interesting! Could you please help me with that?
[Error full text](https://pastebin.com/7nBTusbP)

**Comment by the1schwartz** [comment]
Ah it looks like you are missing this dependency which is needed for desktop platforms like mac and windows:
https://github.com/GameAnalytics/defold-openssl/archive/master.zip

Let me know if that works so I know if I can close this issue.

**Comment by Lampogolovii** [comment]
oh, sorry for that!
I've missed ssl-dependency after merging from one project to another.
Now it works nice and smooth!! Thanks!
You are awesome, guys!

**Comment by the1schwartz** [comment]
Great, you are welcome :)
