### ISSUE TITLE
[2019-02-27 13:27:13.450] [gameanalytics] [warning] Warning/GameAnalytics: Database too large. Event has been blocked.  [2019-02-27 13:27:13.450] [gameanalytics] [warning] Warning/GameAnalytics: Database too large. Event has been blocked.

### ISSUE THREAD

**Issue by subsoap** [GameAnalytics/GA-SDK-DEFOLD#4]
What to do about this?

I also have

```
[2019-02-27 13:27:38.291] [gameanalytics] [error] Error/GameAnalytics: SQLITE3 PREPARE ERROR: library routine called out of sequence
```

**Comment by subsoap** [comment]
```
[2019-02-27 13:32:13.691] [gameanalytics] [warning] Warning/GameAnalytics: Could not add resource event: Datastore not initialized
```

**Comment by subsoap** [comment]
```
[2019-02-27 14:06:28.794] [gameanalytics] [error] Error/GameAnalytics: Error on GA thread

[2019-02-27 14:06:28.794] [gameanalytics] [error] Error/GameAnalytics: Type is not convertible to string
```

**Comment by subsoap** [comment]
"fixed" these by deleting my local GA folder ```C:\Users\Brian\AppData\Local\GameAnalytics```

I also added a thing to our game to hash tracebacks so we don't flood GA with duplicate errors. Instead only one unique traceback is possible to be sent per session per user. More useful now since we will see more common errors instead of 99999999 errors from a single user experiencing a catastrophic bug.

**Comment by subsoap** [comment]
![err](https://user-images.githubusercontent.com/409170/53535287-24108780-3ab7-11e9-89cd-a6ac8a9796b4.png)

Example for anyone who sees this

**Comment by the1schwartz** [comment]
Is this fixed now? I am not really sure if I need to fix something or not in the SDK at the moment? :)

**Comment by subsoap** [comment]
Have not had the errors appear in console since clearing old GA data. I guess this can be closed now, but still useful to be searchable in the future. I'll reopen if it appears again.
