### ISSUE TITLE
Move Linux folder to ~/.config/GameAnalytics

### ISSUE THREAD

**Issue by subsoap** [GameAnalytics/GA-SDK-DEFOLD#7]
Currently it creates a folder

~/GameAnalytics

It should however be

~/.config/GameAnalytics

Ideally it would be nice if we could set this folder.

**Comment by the1schwartz** [comment]
This should now be possible in the latest version (v2.2.0). The document page has been updated on how to this: https://gameanalytics.com/docs/item/defold-sdk#configuring-game-project

Taken from the documentation page:
[gameanalytics]
write_path_osx = $HOME/test/test1/test2
write_path_windows = %USERPROFILE%/test/test1/test2
write_path_linux = $HOME/test/test1/test2

Any missing directories in the path will also be created.

**Comment by subsoap** [comment]
Great thank you!
